version: "3"
services:
  deepstream-peoplenet:
    container_name: deepstream-peoplenet
    privileged: yes
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      - DISPLAY
    working_dir: /app/src
    tty: true
